sudo: required
services:
  - docker

before_install:
  - docker build -t OT-fantasy-sports/node-server -f Dockerfile.dev .

script:
  - docker run -e CI=true OT-fantasy-sports/node-server npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-north-1"
#   app: "Docker-react"
#   env: "Docker-react-env"
#   bucket_name: "elasticbeanstalk-eu-north-1-076750411957"
#   bucket_path: "Docker-react"
#   on:
#    branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: "$AWS_SECRET_KEY"