sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t talevin2000/node-server-test -f ./server/Dockerfile.dev ./server

script:
  - docker run -e CI=true talevin2000/node-server-test npm test

after_success:
  - docker build -t talevin2000/fantasy-client-react ./client-react
  - docker build -t talevin2000/fantasy-node-server ./server
  - docker build -t talevin2000/fantasy-nginx ./nginx

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push talevin2000/fantasy-client-react
  - docker push talevin2000/fantasy-node-server
  - docker push talevin2000/fantasy-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "ot-fantasy-sports"
  env: "Ot-fantasy-sports-env"
  bucket_name: "elasticbeanstalk-eu-north-1-076750411957"
  bucket_path: "ot-fantasy-sports"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY