version: '3'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./home/node/server:/app
    env_file:
      - .env
  client:
    environment:
      - WDS_SOCKET_PORT=0
    build:
      context: ./client-react
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
