version: "3"

services:
  client:
    image: "talevin2000/fantasy-client-react"
    mem_limit: 128m
    hostname: client
  server:
    image: "talevin2000/fantasy-node-server"
    mem_limit: 128m
    hostname: api
    environment:
      - RAPID_API_KEY=$RAPID_API_KEY
      - RAPID_API_HOST=$RAPID_API_HOST
      - MONGO_URL:$MONGO_URL
  nginx:
    image: "talevin2000/fantasy-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
