version: '3.9'
services:
  node_app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /app/node_modules
      - .:/app
